function Crash

[fichier,chemin]=uigetfile('*.avi;*.mp4','open Video');
cd(chemin)

Result={};

Im_seq = VideoReader([chemin fichier]);
ii=0;
largeur = Im_seq.Width;
hauteur = Im_seq.Height;
num_frame = 1;
max_frame=Im_seq.NumberOfFrames;
img = read(Im_seq,num_frame);
test = img ;
if size(img,3) ==1
test(:,:,2)=img;
test(:,:,3)=img;
end
img = test;
% h = implay(Im_seq);

%% Viewer
h2(1)=figure('position',[200 100 largeur/2 hauteur/2],...
    'units','pixels',...
    'numbertitle','off',...
    'name','Viewer',...
    'menubar','none',...
    'color',[0.3 0.3 0.7],...
    'tag','interface');
h2(2)=uicontrol('parent',h2(1),...
    'units','normalized',...
    'position',[0.05 0.05 0.9 0.9],...
    'CData',imresize(test,.5));


%% Image Browser
h(1)=figure('position',[200 100 400 100],...
    'units','pixels',...
    'numbertitle','off',...
    'name','Image Browser',...
    'menubar','none',...
    'color',[0.3 0.3 0.7],...
    'tag','interface');

h(2)=uicontrol('parent',h(1),...
    'style','slider',...
    'Min',1,'Max',max_frame,'Value',num_frame,...
    'SliderStep',[1/(max_frame-1) 1/(max_frame-1)],...
    'units','normalized',...
    'Position',[0.1 0.6 0.8 0.3],...
    'callback',@actu_frame);

h(3)=uicontrol('parent',h(1),...
    'style','edit',...
    'value',num_frame,...
    'string',num2str(num_frame),...
    'units','normalized',...
    'position',[0.4 0.3 0.2 0.2],...
    'callback',@actu_edit);

h(4)=uicontrol('parent',h(1),...
    'style','pushbutton',...
    'string','Event',...
    'units','normalized',...
    'position',[0.7 0.3 0.2 0.2],...
    'callback',@put_remark);
    
h(5)=uicontrol('parent',h(1),...
    'style','pushbutton',...
    'string','Save',...
    'units','normalized',...
    'position',[0.7 0.1 0.2 0.2],...
    'callback',@save);

h(6)=uicontrol('parent',h(1),...
    'style','pushbutton',...
    'string','Quit',...
    'units','normalized',...
    'position',[0.1 0.1 0.2 0.15],...
    'callback',@ending);

h(7)=uicontrol('parent',h(1),...
    'style','pushbutton',...
    'string','Import',...
    'units','normalized',...
    'position',[0.1 0.25 0.2 0.15],...
    'callback',@import_video);

h(8)=uicontrol('parent',h(1),...
    'style','pushbutton',...
    'string','BodyLength',...
    'units','normalized',...
    'position',[0.1 0.4 0.2 0.15],...
    'callback',@body_length);

h(9)=uicontrol('parent',h(1),...
    'style','slider',...
    'Min',0,'Max',2,'Value',1,...
    'SliderStep',[0.05 0.05],...
    'units','normalized',...
    'position',[0.4 0.1 0.2 0.2],...
    'callback',@actu_alpha);


    function actu_alpha(obj,event)
        al_val=get(h(9),'Value');
        img2 = imadjust(img,[],[],al_val);

        set(h2(2),'CData',img2)
    end

    function body_length(obj,event)
        
        temp=figure('numbertitle','off',...
            'menubar','none',...
            'name','Select Region Of Interest',...
            'color',[0.3 0.3 0.7]);
        imshow(img)
        pos=imrect;
        cadre=getPosition(pos);
        centre=[cadre(1)+cadre(3)/2 cadre(2)+cadre(4)/2];
        cadre(3:4)=max([cadre(3) cadre(4)]);
        cadre(1)=centre(1)-cadre(3)/2; cadre(2)=centre(2)-cadre(4)/2;
        
        close(temp)
        
        croppedImage = imcrop(img, cadre);
        v2=figure('numbertitle','off',...
            'menubar','none',...
            'name','Select points and press enter',...
            'color',[0.3 0.3 0.7]);
        imagesc(croppedImage);
        colormap(gray)
        axis off
        
        ligne=imline;
        coor=getPosition(ligne);x=coor(:,1);y=coor(:,2);
        
        length=sqrt((x(2)-x(1))^2+(y(2)-y(1))^2);
        data = [x(1) y(1) x(2) y(2)  length];
        
        b2(1)=figure('position',[300 200 200 100],...
            'units','pixels',...
            'numbertitle','off',...
            'name','Save',...
            'menubar','none',...
            'color',[0.3 0.3 0.7],...
            'tag','interface');
        
        b2(2)=uicontrol('parent',b2(1),...
            'style','pushbutton',...
            'string','Save',...
            'units','normalized',...
            'position',[0.1 0.35 0.3 0.3],...
            'callback',@save_length);
        
        b2(3)=uicontrol('parent',b2(1),...
            'style','pushbutton',...
            'string','Cancel',...
            'units','normalized',...
            'position',[0.6 0.35 0.3 0.3],...
            'callback',@close_length);
        
        function save_length(obj,event)
            [fichier_out,chemin_out]=uiputfile('*.xls','Enregistrer la valeur');
            xlswrite(fullfile(chemin_out,fichier_out),data)
            
            close(v2)
            close(b2(1))
        end
        
        function close_length(obj,event)
            close(v2)
            close(b2(1))
        end

    end

    function actu_frame(obj,event)
        num_frame=round(get(h(2),'Value'));
        img = read(Im_seq,num_frame);
        test = img ;
if size(img,3) ==1
test(:,:,2)=img;
test(:,:,3)=img;
end
img = imresize(test,.5);
        al_val=get(h(9),'Value');
        img2 = imadjust(img,[],[],al_val);

        set(h2(2),'CData',img2)
        set(h(3),'value',num_frame)
        set(h(3),'string',num2str(num_frame))
    end

    function actu_edit(obj,event)
        new_value=str2num(get(h(3),'string')); %#ok<ST2NM>
        set(h(3),'value',new_value)
        num_frame=round(get(h(3),'Value'));
        img = read(Im_seq,num_frame);
        test = img ;
if size(img,3) ==1
test(:,:,2)=img;
test(:,:,3)=img;
end
img = imresize(test,.5);
        al_val=get(h(9),'Value');
        img2 = imadjust(img,[],[],al_val);

        set(h2(2),'CData',img2)
        set(h(2),'value',num_frame)
    end

    function put_remark(obj,event)
        r(1)=figure('position',[300 300 200 125],...
            'units','pixels',...
            'numbertitle','off',...
            'name','Event trigger',...
            'menubar','none',...
            'color',[0.3 0.3 0.7],...
            'tag','interface');
        
        r(2)=uicontrol('parent',r(1),...
            'style','text',...
            'units','normalized',...
            'horizontalalignment','left',...
            'string','Enter a name for the event',...
            'BackgroundColor',[0.3 0.3 0.7],...
            'position',[0.1 0.5 0.8 0.3]);
    
        r(4)=uicontrol('parent',r(1),...
            'style','pushbutton',...
            'string','OK',...
            'units','normalized',...
            'position',[0.75 0.1 0.15 0.15],...
            'callback',@entry);
        
        r(3)=uicontrol('parent',r(1),...
            'style','edit',...
            'units','normalized',...
            'horizontalalignment','left',...
            'string','',...
            'position',[0.1 0.3 0.8 0.3],...
            'callback',@entry);
        
        
        function entry(obj,event)
            ii=ii+1;
            Result{ii,1}=get(r(3),'string');
            Result{ii,2}=num_frame;
            close(r(1))
        end
    end


%% Save

    function save(obj,event)
        [fichier_out,chemin_out]=uiputfile('*.xls','Enregistrer les résultats');
        xlswrite(fullfile(chemin_out,fichier_out),Result)
        
        s(1)=figure('position',[300 300 100 75],...
            'units','pixels',...
            'numbertitle','off',...
            'name','',...
            'menubar','none',...
            'color',[0.2 0.8 0.1],...
            'tag','interface');
        s(2)=uicontrol('parent',s(1),...
            'units','normalized',...
            'position',[0.1 0.1 0.8 0.8],...
            'style','text',...
            'string','Data Saved',...
            'backgroundcolor',[0.2 0.8 0.1],...
            'FontSize',14);
        
        beep
        pause(1)
        
        close(s(1))
        set(h(1),'color',[0.1 0.8 0.1])
    end

    function ending(obj,event)
        close all
        clear all
    end

    function import_video(obj,event)
        [fichier,chemin]=uigetfile('*.avi','Ouvrir une vidéo');
        cd(chemin)
        
        Result={};
        Im_seq = VideoReader([chemin fichier]);
        ii=0;
        largeur = Im_seq.Width;
        hauteur = Im_seq.Height;
        num_frame = 1;
        max_frame=Im_seq.NumberOfFrames;
        img = read(Im_seq,num_frame);
        test = img ;
if size(img,3) ==1
test(:,:,2)=img;
test(:,:,3)=img;
end
img = test;
        set(h2(2),'CData',img)
        set(h(3),'value',num_frame)
        set(h(3),'string',num2str(num_frame))
        set(h(2),'value',num_frame)
        set(h(2),'max',max_frame)
        set(h(2),'SliderStep',[1/(max_frame-1) 1/(max_frame-1)])
        set(h(1),'color',[0.3 0.3 0.7])
    end
%     
%     
% 
% 
% imshow(img)
end